In [1]:
import numpy as np
import pandas as pd

In [2]:
data_set = pd.read_csv('Zomato_Review.txt', delimiter = '\t', quoting = 3 )

In [3]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
#Certainly! The code you've provided appears to be a Python script that uses the Natural Language Toolkit (NLTK) library to perform text preprocessing tasks. Let me explain each line of the code step by step:

# 1. `import re`: This line imports the Python `re` module, which stands for "regular expressions." Regular expressions are used for pattern matching and manipulation of strings. In this code, `re` will be used for text processing tasks.

# 2. `import nltk`: This line imports the Natural Language Toolkit (NLTK), a popular Python library for natural language processing and text analysis.

# 3. `nltk.download('stopwords')`: This line downloads the NLTK dataset for stopwords. Stopwords are common words (e.g., "the," "and," "is") that are often removed from text during text preprocessing tasks because they typically do not carry much meaning.

# 4. `from nltk.corpus import stopwords`: This line imports the `stopwords` module from the NLTK corpus. The `stopwords` module provides a list of common stopwords for various languages.

# 5. `from nltk.stem.porter import PorterStemmer`: This line imports the `PorterStemmer` class from the NLTK library. The Porter Stemmer is a widely used algorithm for stemming, which reduces words to their root or base form. For example, it can convert words like "running," "ran," and "runner" to the common root "run."

# Each line of code in this script imports necessary libraries and resources for text preprocessing tasks, setting the stage for further text analysis or processing.

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\neelv\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
corpus = []
for i in range(0,1000):
    zomato_ratings = re.sub('[^a-zA-Z]', ' ' , data_set['Review'][i])
    print(zomato_ratings)
    print()
    zomato_ratings = zomato_ratings.lower()
    print(zomato_ratings)
    print()
    zomato_ratings = zomato_ratings.split()
    print(zomato_ratings)
    print()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    zomato_ratings = [ps.stem(word) for word in zomato_ratings if not word in set(all_stopwords)]
    print(zomato_ratings)
    print()
    zomato_ratings = ' '.join(zomato_ratings)
    print(zomato_ratings)
    corpus.append(zomato_ratings)

Wow    Loved this place 

wow    loved this place 

['wow', 'loved', 'this', 'place']

['wow', 'love', 'place']

wow love place
Crust is not good 

crust is not good 

['crust', 'is', 'not', 'good']

['crust', 'not', 'good']

crust not good
Not tasty and the texture was just nasty 

not tasty and the texture was just nasty 

['not', 'tasty', 'and', 'the', 'texture', 'was', 'just', 'nasty']

['not', 'tasti', 'textur', 'nasti']

not tasti textur nasti
Stopped by during the late May bank holiday off Rick Steve recommendation and loved it 

stopped by during the late may bank holiday off rick steve recommendation and loved it 

['stopped', 'by', 'during', 'the', 'late', 'may', 'bank', 'holiday', 'off', 'rick', 'steve', 'recommendation', 'and', 'loved', 'it']

['stop', 'late', 'may', 'bank', 'holiday', 'rick', 'steve', 'recommend', 'love']

stop late may bank holiday rick steve recommend love
The selection on the menu was great and so were the prices 

the selection on the menu was great an

['watch', 'price', 'inflat', 'portion', 'get', 'smaller', 'manag', 'attitud', 'grow', 'rapidli']

watch price inflat portion get smaller manag attitud grow rapidli
Wonderful lil tapas and the ambience made me feel all warm and fuzzy inside 

wonderful lil tapas and the ambience made me feel all warm and fuzzy inside 

['wonderful', 'lil', 'tapas', 'and', 'the', 'ambience', 'made', 'me', 'feel', 'all', 'warm', 'and', 'fuzzy', 'inside']

['wonder', 'lil', 'tapa', 'ambienc', 'made', 'feel', 'warm', 'fuzzi', 'insid']

wonder lil tapa ambienc made feel warm fuzzi insid
 I got to enjoy the seafood salad  with a fabulous vinegrette  

 i got to enjoy the seafood salad  with a fabulous vinegrette  

['i', 'got', 'to', 'enjoy', 'the', 'seafood', 'salad', 'with', 'a', 'fabulous', 'vinegrette']

['got', 'enjoy', 'seafood', 'salad', 'fabul', 'vinegrett']

got enjoy seafood salad fabul vinegrett
 The wontons were thin  not thick and chewy  almost melt in your mouth  

 the wontons were thin  not th

In [7]:
print(corpus)

['wow love place', 'crust not good', 'not tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'the select menu great price', 'now i get angri i want damn pho', 'honeslti tast that fresh', 'the potato like rubber could tell made ahead time kept warmer', 'the fri great', 'a great touch', 'servic prompt', 'would not go back', 'the cashier care ever i say still end wayyy overpr', 'i tri cape cod ravoli chicken cranberri mmmm', 'i disgust i pretti sure human hair', 'i shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'thi place not worth time let alon vega', 'not like', 'the burritto blah', 'the food amaz', 'servic also cute', 'i could care less the interior beauti', 'so perform', 'that right red velvet cake ohhh stuff good', 'they never brought salad ask', 'thi hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm our sever run around like total overwhelm', 'the worst salmon sashimi', 'also comb

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(corpus).toarray()
y = data_set.iloc[:,-1].values
print(X)
print()
print(y)
# X = cv.fit_transform(corpus).toarray(): This line fits the CountVectorizer on the corpus data and transforms 
# the text data into a numerical feature matrix X. toarray() converts the sparse matrix into a dense NumPy array. 
# Each row in X represents a document (from the corpus), and each column represents a unique word or token. 
# The values in X represent the counts of each word in the respective documents.

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

[1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 1 1
 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0
 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1
 1 0 1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1
 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 1 1
 0 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 0 1 1 1
 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1
 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [77]:
from sklearn.naive_bayes import GaussianNB
Classifier = GaussianNB()
Classifier.fit(X_train,y_train)

GaussianNB()

In [78]:
y_predict = Classifier.predict(X_test)

In [79]:
print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score, r2_score

In [81]:
cm = confusion_matrix(y_test, y_predict)
print(cm)
print()
print(accuracy_score(y_test, y_predict))
print()
print(r2_score(y_test, y_predict))

[[55 42]
 [11 92]]

0.735

-0.060954859373436365
