In [16]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
new_array = array.reshape(4,3)
print(new_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
new_array = array.reshape(2,3,2)
print(new_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
