In [2]:
import numpy as np
import pandas as pd

In [3]:
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/80/6f/57d36f6507e432d7fc1956b2e9e8530c5c2d2bfcd8821bcbfae271cd6688/tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.14.0 from https://files.pythonhosted.org/packages/ad/6e/1bfe367855dd87467564f7bf9fa14f3b17889988e79598bc37bf18f5ffb6/tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ---------------------------------------- 57.5

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.14.0'

In [6]:
data_set = pd.read_csv('American Express User Exit Prediction.csv')
X = data_set.iloc[:,0:-1].values
y = data_set.iloc[:,-1].values

In [7]:
print(X)
print(y)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]
[0 0 0 ... 0 1 0]


In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:,2] = label_encoder.fit_transform(X[:,2])

In [10]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)
print()
print(X_test)

[[ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -0.06854301]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
   0.34018176]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.67326188]
 ...
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
  -0.17067658]
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.4232319 ]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -1.67963883]]

[[-0.99397585 -0.58161408  1.73088875 ... -0.95444587  0.63134107
   1.46462434]
 [-0.99397585 -0.58161408  1.73088875 ...  0.86555365  0.63134107
  -1.20908669]
 [ 1.00606066 -0.58161408 -0.57773788 ...  0.86555365  0.63134107
  -1.70583967]
 ...
 [ 1.00606066 -0.58161408 -0.57773788 ...  0.86555365 -1.5839299
   0.14691931]
 [ 1.00606066 -0.58161408 -0.57773788 ... -0.95444587 -1.5839299
  -0.57566677]
 [ 1.00606066 -0.58161408 -0.57773788 ... -0.95444587  0.63134107
   1.68962743]]


In [66]:
#ANN initialization
ann = tf.keras.models.Sequential()

In [67]:
#Input and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [68]:
# 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [69]:
# output layer
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

In [70]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [71]:
#Training on training dataset
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 1s 1ms/step - loss: 0.5744 - accuracy: 0.7275
Epoch 2/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4753 - accuracy: 0.7961
Epoch 3/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4563 - accuracy: 0.7944
Epoch 4/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4455 - accuracy: 0.7942
Epoch 5/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4393 - accuracy: 0.7950
Epoch 6/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4351 - accuracy: 0.7957
Epoch 7/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4322 - accuracy: 0.8020
Epoch 8/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4299 - accuracy: 0.8064
Epoch 9/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4280 - accuracy: 0.8098
Epoch 10/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4261 - accura

249/249 [==============================] - 0s 981us/step - loss: 0.3488 - accuracy: 0.8539
Epoch 82/120
249/249 [==============================] - 0s 946us/step - loss: 0.3486 - accuracy: 0.8542
Epoch 83/120
249/249 [==============================] - 0s 953us/step - loss: 0.3482 - accuracy: 0.8532
Epoch 84/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3482 - accuracy: 0.8535
Epoch 85/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3477 - accuracy: 0.8548
Epoch 86/120
249/249 [==============================] - 0s 1ms/step - loss: 0.3478 - accuracy: 0.8529
Epoch 87/120
249/249 [==============================] - 0s 960us/step - loss: 0.3474 - accuracy: 0.8540
Epoch 88/120
249/249 [==============================] - 0s 968us/step - loss: 0.3475 - accuracy: 0.8538
Epoch 89/120
249/249 [==============================] - 0s 969us/step - loss: 0.3471 - accuracy: 0.8559
Epoch 90/120
249/249 [==============================] - 0s 958us/step - loss: 0.347

In [84]:
print(ann.predict(sc.transform([[0.0, 0.0, 1.0 , 649, 1, 61, 4 , 1739005,2, 1, 86816]]))>0.5)

1/1 [==============================] - 0s 16ms/step
[[ True]]


In [73]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(-1,1), y_test.reshape(-1,1)),1))

63/63 [==============================] - 0s 764us/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score, r2_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print()
print(accuracy_score(y_test, y_pred))
print()
print(r2_score(y_test, y_pred))

[[1498   75]
 [ 225  188]]

0.8489425981873112

0.0828893756474649
